### PR TITLE
add vim-dirvish highlighting

### PR DESCRIPTION
**Pull request by eemed**
I would like to add highlighting to vim-dirvish directory tree.
Before:
before

After:
dirvish

Directories are blue, and items added to the argslist are orange.

### CODE REVIEW

**Comment by cideM** [comment]
Thanks for the suggestion! The thing is that I'm really trying to limit the use of colors in this colorscheme, and instead use bold, italic and underline a bit more. Maybe making directories bold and keeping the underline for arglist would work?

**Comment by eemed** [comment]
I did a did a little bit of testing, the bold folders look good but I don't really think the underline is good for arglist.

**Comment by eemed** [comment]
Changed the arglist to underline and directories to bold.
plain

**Comment by cideM** [comment]
:+1: looks good, can you rebase and squash the commits into one? Then I can merge it

**Comment by eemed** [comment]
Should be good to go

**Comment by eemed** [comment]
Should be good to go.

**Pull request merged**
